
CREATE SCHEMA ACTUAL;


CREATE TABLE ACTUAL.CLIENT (
    ID serial PRIMARY KEY NOT NULL,
    NAME VARCHAR (100) NULL,
    PERSONAL_ID INT NULL
);

CREATE TABLE ACTUAL.ADDRESS (
    CLIENT_ID INT NULL,
   	ADDRESS VARCHAR (100) NULL
);

CREATE TABLE ACTUAL.CREDITCARD (
    CLIENT_ID INT NULL,
   	CREDITCARD VARCHAR(50) NULL
);

CREATE TABLE ACTUAL.EMAIL (
    CLIENT_ID INT NULL,
   	CREDITCARD VARCHAR (100) NULL
);

CREATE TABLE ACTUAL.ORDERNUMBER (
    CLIENT_ID INT NULL,
   	ORDERNUMBER INT NULL
);

CREATE TABLE ACTUAL.TELEPHONE (
    CLIENT_ID INT NULL,
   	TELEPHONE VARCHAR (50) NULL
);